//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgTehProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemInZakaz
    {
        public int Id_ItemInZacaz { get; set; }
        public int Id_Zakaz { get; set; }
        public int Id_Basket { get; set; }
    
        public virtual Basket Basket { get; set; }
        public virtual Zakaz Zakaz { get; set; }
    }
}
